services:
  backend:
    image: ghcr.io/jamieredding/pair-stairs-backend:latest
    hostname: backend
    container_name: pair_stairs_backend
    restart: unless-stopped
    env_file: docker-compose.env
    networks:
      - pair_stairs
    ports:
      - "18081:8080"
    depends_on:
      - db

  frontend:
    image: ghcr.io/jamieredding/pair-stairs-frontend:latest
    hostname: frontend
    container_name: pair_stairs_frontend
    restart: unless-stopped
    environment:
      - BACKEND_HOST=http://backend:8080
    networks:
      - pair_stairs
    ports:
      - "18082:80"
    depends_on:
      - backend

  db:
    image: mysql:8.4.0
    hostname: db
    container_name: pair_stairs_db
    restart: unless-stopped
    env_file: docker-compose.env
    networks:
      - pair_stairs
    ports:
      - "18083:3306"
    volumes:
      - pair_stairs_db:/var/lib/mysql

volumes:
  pair_stairs_db:

networks:
  pair_stairs:
