### Get developers

GET {{baseUrl}}/api/v1/developers

### Get Developer info

GET {{baseUrl}}/api/v1/developers/info

### New developer

POST {{baseUrl}}/api/v1/developers
Content-Type: application/json

{
  "name": "new developer"
}

### Patch developer
PATCH {{baseUrl}}/api/v1/developers/1
Content-Type: application/json

{
  "archived": true
}

### Get streams

GET {{baseUrl}}/api/v1/streams

### Get stream info

GET {{baseUrl}}/api/v1/streams/info

### Patch stream

PATCH {{baseUrl}}/api/v1/streams/1
Content-Type: application/json

{
  "archived": true
}

### Calculate combinations

POST {{baseUrl}}/api/v1/combinations/calculate?page=1
Content-Type: application/json

{
  "developerIds": [
    0,
    1,
    2
  ],
  "streamIds": [
    0,
    1
  ]
}

### Save combination event

POST {{baseUrl}}/api/v1/combinations/event
Content-Type: application/json

{
  "date": "2024-04-27",
  "combination": [
    {
      "developerIds": [1, 2],
      "streamId": 1
    },
    {
      "developerIds": [3],
      "streamId": 2
    }
  ]
}

### Get combination events

GET {{baseUrl}}/api/v1/combinations/event?page=0

### Delete combination event

DELETE {{baseUrl}}/api/v1/combinations/event/1


### Teams
@slug = team-0
@name = Team 0

### Get team
GET {{baseUrl}}/api/v1/teams/{{slug}}

### New team
POST {{baseUrl}}/api/v1/teams
Content-Type: application/json

{
  "name": "{{name}}",
  "slug": "{{slug}}"
}



### Feature flags
GET {{baseUrl}}/api/v1/feature-flags

### Actuator

### health
GET {{baseUrl}}/actuator/health

### readiness
GET {{baseUrl}}/actuator/health/readiness

### liveness
GET {{baseUrl}}/actuator/health/liveness

### info
GET {{baseUrl}}/actuator/info

### prometheus
GET {{baseUrl}}/actuator/prometheus
