### Get developers

GET {{baseUrl}}/api/v1/developers

### Get Developer info

GET {{baseUrl}}/api/v1/developers/info

### New developer

POST {{baseUrl}}/api/v1/developers
Content-Type: application/json

{
  "name": "new developer"
}

### Get streams

GET {{baseUrl}}/api/v1/streams

### Get stream info

GET {{baseUrl}}/api/v1/streams/info

### Calculate combinations

POST {{baseUrl}}/api/v1/combinations/calculate
Content-Type: application/json

{
  "developerIds": [
    0,
    1,
    2
  ],
  "streamIds": [
    0,
    1
  ]
}

### Save combination event

POST {{baseUrl}}/api/v1/combinations/event
Content-Type: application/json

{
  "date": "2024-04-27",
  "combination": [
    {
      "developerIds": [1, 2],
      "streamId": 1
    },
    {
      "developerIds": [3],
      "streamId": 2
    }
  ]
}
