### Get developers

GET {{baseUrl}}/api/v1/developers

### Get Developer info

GET {{baseUrl}}/api/v1/developers/info

### New developer

POST {{baseUrl}}/api/v1/developers
Content-Type: application/json

{
  "name": "new developer"
}

### Get streams

GET {{baseUrl}}/api/v1/streams

### Get stream info

GET {{baseUrl}}/api/v1/streams/info

### Calculate combinations

POST {{baseUrl}}/api/v1/combinations/calculate
Content-Type: application/json

{
  "developerIds": [
    0,
    1,
    2
  ],
  "streamIds": [
    0,
    1
  ]
}
