services:
  pair_stairs_web:
    image: ghcr.io/jamieredding/pair-stairs-web:latest
    hostname: web
    restart: unless-stopped
    networks:
      - pair_stairs_net
    ports:
      - "${BACKEND_PORT}:8080"
    volumes:
      - "./application.properties:/opt/application.properties"
      - "./old-schemas/build/h2_v1_database.mv.db:/opt/h2_v1_database.mv.db"
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:8080/actuator/health/readiness | grep -q 'UP' || exit 1"]
      interval: 2s
      timeout: 3s
      retries: 60
      start_period: 1m

networks:
  pair_stairs_net:
