services:
  pair_stairs_backend:
    image: ghcr.io/jamieredding/pair-stairs-backend:latest
    hostname: backend
    restart: unless-stopped
    networks:
      - pair_stairs_net
    ports:
      - "${BACKEND_PORT}:8080"
    volumes:
      - "./application.properties:/opt/application.properties"
      - "pair_stairs_h2:/opt/h2"

  pair_stairs_frontend:
    image: ghcr.io/jamieredding/pair-stairs-frontend:latest
    hostname: frontend
    restart: unless-stopped
    environment:
      - BACKEND_HOST=http://backend:8080
    networks:
      - pair_stairs_net
    ports:
      - "${FRONTEND_PORT}:80"
    depends_on:
      - pair_stairs_backend


volumes:
  pair_stairs_h2:

networks:
  pair_stairs_net:
