services:
  pair_stairs_web:
    image: ghcr.io/jamieredding/pair-stairs-web:latest
    hostname: web
    restart: unless-stopped
    networks:
      - pair_stairs_net
    ports:
      - "${BACKEND_PORT}:8080"
    volumes:
      - "./application.properties:/opt/application.properties"
      - "pair_stairs_h2:/opt/h2"
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:8080/actuator/health/readiness | grep -q 'UP' || exit 1"]
      interval: 2s
      timeout: 3s
      retries: 60
      start_period: 1m
    depends_on:
      oauth:
        condition: service_healthy

  oauth:
    image: ghcr.io/dexidp/dex:latest
    container_name: oauth
    ports:
      - 5556:5556
    networks:
      - pair_stairs_net
    volumes:
      - ./oauth/config.docker.yaml:/etc/dex/config.docker.yaml
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:5556/dex/healthz | grep -q 'Health check passed' || exit 1"]
      interval: 2s
      timeout: 3s
      retries: 60
      start_period: 1m

volumes:
  pair_stairs_h2:

networks:
  pair_stairs_net:
