### Reset all scenarios
POST {{baseUrl}}/__admin/scenarios/reset

### Reset developers scenario
PUT {{baseUrl}}/__admin/scenarios/Developers/state

### Reset streams scenario
PUT {{baseUrl}}/__admin/scenarios/Streams/state

### Reset teams scenario
PUT {{baseUrl}}/__admin/scenarios/Teams/state

### Disable teams
PUT {{baseUrl}}/__admin/scenarios/Teams/state
Content-Type: application/json

{
  "state": "DISABLED"
}

### Enable developer archive flow
PUT {{baseUrl}}/__admin/scenarios/ARCHIVE_DEVELOPERS/state
Content-Type: application/json

{
  "state": "ENABLED"
}

### Enable stream archive flow
PUT {{baseUrl}}/__admin/scenarios/ARCHIVE_STREAMS/state
Content-Type: application/json

{
  "state": "ENABLED"
}

### Get scenarios
GET {{baseUrl}}/__admin/scenarios

### Remove manual stubbing
POST {{baseUrl}}/__admin/mappings/reset

### Manual stubbing
POST {{baseUrl}}/__admin/mappings
Content-Type: application/json

{
  "priority": 1,
  "request": {
    "method": "POST",
    "url": "/123"
  },
  "response": {
    "status": 200
  }
}