issuer: http://oauth:5556/dex

storage:
  type: memory

web:
  http: 0.0.0.0:5556

logger:
  level: "debug"
  format: "text" # can also be "json"

oauth2:
  passwordConnector: local

staticClients:
  - id: "{{ .Env.OAUTH_CLIENT_ID }}"
    redirectURIs:
      - 'http://web:8080/login/oauth2/code/oauth'
      - 'http://localhost:28081/login/oauth2/code/oauth'
    name: 'Pair Stairs'
    secret: "{{ .Env.OAUTH_CLIENT_SECRET }}"

enablePasswordDB: true

staticPasswords:
  - email: "admin@example.com"
    # bcrypt hash of the string "password": $(echo password | htpasswd -BinC 10 admin | cut -d: -f2)
    hash: "$2a$10$2b2cU8CPhOTaGrs1HRQuAueS7JTT5ZHsHSzYiFPm1leZck7Mc8T4W"
    username: "admin"
    userID: "08a8684b-db88-4b73-90a9-3cd1661f5466"