services:
  pair_stairs_backend:
    image: ghcr.io/jamieredding/pair-stairs-backend:latest
    hostname: backend
    restart: unless-stopped
    env_file: application.env
    networks:
      - pair_stairs_net
    ports:
      - "${BACKEND_PORT}:8080"
# Example of mounting your own properties
#    volumes:
#      - "./application.properties:/opt/application.properties"
    depends_on:
      - pair_stairs_db

  pair_stairs_frontend:
    image: ghcr.io/jamieredding/pair-stairs-frontend:latest
    hostname: frontend
    restart: unless-stopped
    environment:
      - BACKEND_HOST=http://backend:8080
    networks:
      - pair_stairs_net
    ports:
      - "${FRONTEND_PORT}:80"
    depends_on:
      - pair_stairs_backend

  pair_stairs_db:
    image: mysql:9.4.0
    hostname: db
    restart: unless-stopped
    env_file: application.env
    networks:
      - pair_stairs_net
    ports:
      - "${DB_PORT}:3306"
    volumes:
      - pair_stairs_db:/var/lib/mysql

volumes:
  pair_stairs_db:

networks:
  pair_stairs_net:
