name: build_image

services:
  db:
    image: mysql:9.4.0
    ports:
      - "${DB_PORT}:3306"
    env_file:
      - .env
    healthcheck:
      # Waits until MySQL responds
      test: ["CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -uroot -p${MYSQL_ROOT_PASSWORD} || exit 1"]
      interval: 2s
      timeout: 3s
      retries: 60
      start_period: 1m

  oauth:
    image: ghcr.io/dexidp/dex:latest
    ports:
      - 5556:5556
    volumes:
      - ./oauth/config.docker.yaml:/etc/dex/config.docker.yaml
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:5556/dex/healthz | grep -q 'Health check passed' || exit 1"]
      interval: 2s
      timeout: 3s
      retries: 60
      start_period: 1m