name: build_image

services:
  db:
    image: mysql:9.4.0
    container_name: pair_stairs_db
    ports:
      - "${DB_PORT}:3306"
    env_file:
      - .env
    healthcheck:
      # Waits until MySQL responds
      test: ["CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -uroot -p${MYSQL_ROOT_PASSWORD} || exit 1"]
      interval: 2s
      timeout: 3s
      retries: 60
      start_period: 1m

#  oauth:
#    image: wiremock/wiremock:3.5.2
#    container_name: oauth
#    command: ["--verbose"]
#    ports:
#      - "${OAUTH_PORT}:8080"
#    env_file:
#      - .env
#    volumes:
#      - ./wiremock-oauth2:/home/wiremock
#    healthcheck:
#      # Simple check against admin endpoint
#      test: ["CMD-SHELL", "wget -qO- http://127.0.0.1:8080/__admin/ | grep -q mappings || exit 1"]
#      interval: 2s
#      timeout: 3s
#      retries: 30
#      start_period: 2s
  oauth:
    image: ghcr.io/dexidp/dex:latest
    container_name: oauth
    ports:
      - 5556:5556
    volumes:
      - ./oauth/config.docker.yaml:/etc/dex/config.docker.yaml
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:5556/dex/healthz | grep -q 'Health check passed' || exit 1"]
      interval: 2s
      timeout: 3s
      retries: 60
      start_period: 1m